### ISSUE TITLE
create vsi from image_id failed for blockDevices

### ISSUE THREAD

**Issue by leibaogit** [softlayer/terraform-provider-softlayer#107]
I have a image templete and want to create a vsi by the python API. It always fails with this reason: "Invalid value provided for 'blockDevices'. Block devices may not be provided when using an image template."

```
new_vsi = {
    'domain': u'test01.labs.sftlyr.ws',
    'hostname': u'minion05',
    'datacenter': u'hkg02',
    'dedicated': False,
    'private': False,
    'cpus': 1,
    'image_id' : 1498971,
    #'os_code' : u'UBUNTU_LATEST',
    'hourly': True,
    'ssh_keys': [],
    'disks': ('100','25'),
    'local_disk': True,
    'memory': 1024,
    'tags': 'test, pleaseCancel'
}

vsi_mgr = SoftLayer.VSManager(client)
>>> waf = vsi_mgr.create_instance(**new_vsi)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/managers/vs.py", line 544, in create_instance
    inst = self.guest.createObject(self._generate_create_dict(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/transports.py", line 195, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_InvalidValue): Invalid value provided for 'blockDevices'. Block devices may not be provided when using an image template.
```

```
 #slcli image detail 1498971
:....................:......................................:
:               name : value                                :
:....................:......................................:
:                 id : 1498971                              :
:  global_identifier : d77202f1-daa5-41a7-83bd-2689e843897f :
:               name : waf-modsecurity                      :
:             status : Active                               :
: active_transaction : -                                    :
:            account : 323716                               :
:         visibility : Private                              :
:               type : System                               :
:               flex : False                                :
:               note : None                                 :
:            created : 2017-02-13T16:15:46+08:00            :
:         disk_space : 3.11G                                :
:        datacenters : dal05,dal06,hkg02                    :
:....................:......................................:
```

**Comment by ashishth09** [comment]
@bali2016 did you mean to create these issues against https://github.com/softlayer/softlayer-python?

**Comment by renier** [comment]
@bali2016 Please create this against the python project.
