### ISSUE TITLE
slcli error

### ISSUE THREAD

**Issue by leibaogit** [softlayer/terraform-provider-softlayer#108]
```
# slcli object-storage endpoints
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/object_storage/list_endpoints.py", line 17, in cli
    endpoints = mgr.list_endpoints()
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/managers/object_storage.py", line 48, in list_endpoints
    filter=_filter)['storageNodes']:
TypeError: string indices must be integers, not str

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
```

**Comment by renier** [comment]
@bali2016 This is not the softlayer-python project
