### ISSUE TITLE
Any Idea how to chase this down?

### ISSUE THREAD

**Issue by ghost** [softlayer/terraform-provider-softlayer#187]
```
panic: runtime error: invalid memory address or nil pointer dereference
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1706bd9]
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64:
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: goroutine 5193 [running]:
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: github.com/softlayer/terraform-provider-softlayer/softlayer.resourceSoftLayerFwHardwareDedicatedRulesRead(0xc422131490, 0x18b7660, 0xc42148d9d0, 0x0, 0x0)
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: 	/Users/renier/Projects/go/src/github.com/softlayer/terraform-provider-softlayer/softlayer/resource_softlayer_fw_hardware_dedicated_rules.go:207 +0x739
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4215eaba0, 0xc421fb61e0, 0x18b7660, 0xc42148d9d0, 0xc421608668, 0xc4212b5901, 0x1051e80)
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: 	/Users/renier/Projects/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:314 +0x21d
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc42148d0a0, 0xc421fb6190, 0xc421fb61e0, 0x2500000, 0x0, 0xc420022000)
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: 	/Users/renier/Projects/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x91
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4215415c0, 0xc421352680, 0xc4213528b0, 0x0, 0x0)
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: 	/Users/renier/Projects/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: reflect.Value.call(0xc420283080, 0xc42151e970, 0x13, 0x1991ae1, 0x4, 0xc422f22f20, 0x3, 0x3, 0xc420d346c8, 0x128c4ef, ...)
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: reflect.Value.Call(0xc420283080, 0xc42151e970, 0x13, 0xc420d34720, 0x3, 0x3, 0xc420d3479e, 0xc420d34798, 0x0)
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: net/rpc.(*service).call(0xc42155fbc0, 0xc42155fb80, 0xc421614000, 0xc42160c080, 0xc421563480, 0x17cb0a0, 0xc421352680, 0x16, 0x17cb0e0, 0xc4213528b0, ...)
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: created by net/rpc.(*Server).ServeCodec
2018-06-26T14:12:56.724-0700 [DEBUG] plugin.terraform-provider-softlayer_darwin_amd64: 	/usr/local/go/src/net/rpc/server.go:481 +0x404
2018/06/26 14:12:56 [ERROR] root.atp-sl-tok-oss-pod: eval: *terraform.EvalRefresh, err: softlayer_fw_hardware_dedicated_rules.rules: unexpected EOF
2018/06/26 14:12:56 [ERROR] root.atp-sl-tok-oss-pod: eval: *terraform.EvalSequence, err: softlayer_fw_hardware_dedicated_rules.rules: unexpected EOF
2018/06/26 14:12:56 [TRACE] [walkRefresh] Exiting eval tree: module.atp-sl-tok-oss-pod.softlayer_fw_hardware_dedicated_rules.rules
2018/06/26 14:12:56 [ERROR] root.atp-sl-seo-oss-pod: eval: *terraform.EvalRefresh, err: softlayer_fw_hardware_dedicated_rules.rules: unexpected EOF
2018/06/26 14:12:56 [ERROR] root.atp-sl-seo-oss-pod: eval: *terraform.EvalSequence, err: softlayer_fw_hardware_dedicated_rules.rules: unexpected EOF
2018/06/26 14:12:56 [TRACE] [walkRefresh] Exiting eval tree: module.atp-sl-seo-oss-pod.softlayer_fw_hardware_dedicated_rules.rules
2018/06/26 14:12:56 [ERROR] root.atp-sl-ams-oss-pod: eval: *terraform.EvalRefresh, err: softlayer_fw_hardware_dedicated_rules.rules: unexpected EOF
2018/06/26 14:12:56 [ERROR] root.atp-sl-ams-oss-pod: eval: *terraform.EvalSequence, err: softlayer_fw_hardware_dedicated_rules.rules: unexpected EOF
2018/06/26 14:12:56 [TRACE] [walkRefresh] Exiting eval tree: module.atp-sl-ams-oss-pod.softlayer_fw_hardware_dedicated_rules.rules
```

**Comment by ghost** [comment]
This is an issue with the cloud provider IBM Softlayer and one stubborn firewall.
