### ISSUE TITLE
Issues with latest version and old state

### ISSUE THREAD

**Issue by Ari-E-S** [softlayer/terraform-provider-softlayer#33]
Hi!

I seem to have issues after upgrading to the latest versions of this plugin when refreshing states that already existed.
I found that, if I revert to a previous version, everything works fine.
From what I could test, the latest commit that works well is 084e001745ed44da69f2a9988d24513b9aeea2bc.

Is there anything I'm missing?

Thanks!
   --Ariel

The tail end of crash.log goes like this:

```
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer: panic: runtime error: invalid memory address or nil pointer dereference
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer:   panic: runtime error: invalid memory address or nil pointer dereference
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x43fca6]
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer:
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer: goroutine 32 [running]:
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer: panic(0x722be0, 0xc42000c100)
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer:   /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer: github.com/softlayer/terraform-provider-softlayer/vendor/github.com/renier/xmlrpc.(*clientCodec).ReadResponseHeader.func1(0x0, 0xc420130f50, 0xc4202c1fa8)
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer:   /Users/asalvo/Documents/go/src/github.com/softlayer/terraform-provider-softlayer/vendor/github.com/renier/xmlrpc/client.go:83 +0x26
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer: panic(0x722be0, 0xc42000c100)
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer:   /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer: github.com/softlayer/terraform-provider-softlayer/vendor/github.com/renier/xmlrpc.(*clientCodec).ReadResponseHeader(0xc420130f50, 0xc4202b11a0, 0x0, 0x0)
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer:   /Users/asalvo/Documents/go/src/github.com/softlayer/terraform-provider-softlayer/vendor/github.com/renier/xmlrpc/client.go:89 +0x153
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer: net/rpc.(*Client).input(0xc4202c1f80)
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer:   /usr/local/Cellar/go/1.7.1/libexec/src/net/rpc/client.go:109 +0xbd
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer: created by net/rpc.NewClientWithCodec
2016/10/20 15:54:39 [DEBUG] plugin: terraform-provider-softlayer:   /usr/local/Cellar/go/1.7.1/libexec/src/net/rpc/client.go:201 +0xe4
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalRefresh, err: softlayer_virtual_guest.dom_prd_dc: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalRefresh, err: softlayer_virtual_guest.erp_prd_db: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.erp_prd_db: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalRefresh, err: softlayer_virtual_guest.erp_prd_app: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.erp_prd_app: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalOpFilter, err: softlayer_virtual_guest.erp_prd_app: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.erp_prd_app: unexpected EOF
2016/10/20 15:54:39 [DEBUG] plugin: /Users/asalvo/Documents/go/bin/terraform-provider-softlayer: plugin process exited
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalRefresh, err: softlayer_virtual_guest.pc_prd_ss: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.pc_prd_ss: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalOpFilter, err: softlayer_virtual_guest.pc_prd_ss: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.pc_prd_ss: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalOpFilter, err: softlayer_virtual_guest.erp_prd_db: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.erp_prd_db: unexpected EOF
2016/10/20 15:54:39 [TRACE] [walkRefresh] Exiting eval tree: softlayer_virtual_guest.erp_prd_db
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.dom_prd_dc: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalOpFilter, err: softlayer_virtual_guest.dom_prd_dc: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.dom_prd_dc: unexpected EOF
2016/10/20 15:54:39 [TRACE] [walkRefresh] Exiting eval tree: softlayer_virtual_guest.dom_prd_dc
2016/10/20 15:54:39 [TRACE] [walkRefresh] Exiting eval tree: softlayer_virtual_guest.erp_prd_app
2016/10/20 15:54:39 [TRACE] [walkRefresh] Exiting eval tree: softlayer_virtual_guest.pc_prd_ss
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalRefresh, err: softlayer_virtual_guest.gateway_router: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.gateway_router: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalOpFilter, err: softlayer_virtual_guest.gateway_router: unexpected EOF
2016/10/20 15:54:39 [ERROR] root: eval: *terraform.EvalSequence, err: softlayer_virtual_guest.gateway_router: unexpected EOF
2016/10/20 15:54:39 [TRACE] [walkRefresh] Exiting eval tree: softlayer_virtual_guest.gateway_router
2016/10/20 15:54:39 [DEBUG] vertex provider.softlayer (close), got dep: softlayer_virtual_guest.erp_prd_app
2016/10/20 15:54:39 [DEBUG] vertex provider.softlayer (close), got dep: softlayer_virtual_guest.gateway_router
2016/10/20 15:54:39 [DEBUG] vertex provider.softlayer (close), got dep: softlayer_virtual_guest.dom_prd_dc
2016/10/20 15:54:39 [DEBUG] vertex provider.softlayer (close), got dep: softlayer_virtual_guest.erp_prd_db
2016/10/20 15:54:39 [DEBUG] vertex provider.softlayer (close), got dep: provider.softlayer
2016/10/20 15:54:39 [DEBUG] vertex provider.softlayer (close), got dep: softlayer_virtual_guest.pc_prd_ss
2016/10/20 15:54:39 [DEBUG] vertex root, got dep: provider.softlayer (close)
2016/10/20 15:54:39 [DEBUG] vertex root, got dep: var.vlan_routers
2016/10/20 15:54:39 [DEBUG] vertex root, got dep: var.provider_softlayer_dns_api_key
2016/10/20 15:54:39 [DEBUG] vertex root, got dep: var.provider_softlayer_dns_username
2016/10/20 15:54:39 [DEBUG] plugin: waiting for all plugin processes to complete...
```

**Comment by renier** [comment]
@arielsalvo When you get that error, which revision do you have in vendor/vendor.json for github.com/renier/xmlrpc?

**Comment by Ari-E-S** [comment]
My current setup is consistently showing the error.

```
[$GOPATH/src/github.com/softlayer/terraform-provider-softlayer] master ± git describe --tags
v1.0.0-11-g8d852d2
```

```
[$GOPATH/src] $ find . -name vendor.json
./github.com/hashicorp/terraform/vendor/vendor.json
./github.com/softlayer/terraform-provider-softlayer/vendor/vendor.json
```

./github.com/softlayer/terraform-provider-softlayer/vendor/vendor.json

``` ...
 {
    "checksumSHA1": "PT+MJ+pQrA0UMnM3D/xuqymHM78=",
    "path": "github.com/renier/xmlrpc",
    "revision": "ad26f1fdbf2236f10f1b58e9162add43c2e4bab9",
    "revisionTime": "2016-10-08T07:22:20Z"
},
...
```

[$GOPATH/src/github.com/renier/xmlrpc] master ± git describe --all
heads/master

**Comment by renier** [comment]
@arielsalvo can I bother you for a sample of a .tf I can use to recreate it? I may have a fix already, but not sure until I can exactly recreate and debug.

**Comment by renier** [comment]
@arielsalvo Was able to recreate the problem. Fixed in 26ee572ee3d2ec6727dfcf00cce13fe13d4f2b1b.

BTW, this was a bug in the xmlrpc transport. REST is the default transport, so you must have an xmlrpc endpoint url in your .softlayer file.

**Comment by Ari-E-S** [comment]
Excellent! That seems to have done it....

Indeed, I have an xmlrpc endpoint but I don't think I put it there myself.... I think it was "slcli config setup"

```
endpoint_url = https://api.softlayer.com/xmlrpc/v3.1/
timeout = 0
```

Do you recommend REST as transport?

**Comment by renier** [comment]
@arielsalvo xmlrpc should work fine now. I'm also using it as my default now, so If there are any latent bugs, I'll hit find them.
