### ISSUE TITLE
Terraform crash when creating virtual guest, dies with "unexpected EOF"

### ISSUE THREAD

**Issue by igoraj** [softlayer/terraform-provider-softlayer#51]
Occasionally terraform crashes and reports "unexpected EOF". This seems to happen on random basis.

short excerpt from crash log:
```
panic: runtime error: invalid memory address or nil pointer dereference
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xb2e14]
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer:
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: goroutine 283 [running]:
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: panic(0x72a300, 0xc42000c0b0)
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: github.com/softlayer/terraform-provider-softlayer/softlayer.resourceSoftLayerVirtualGuestRead(0xc4207bff20, 0x7113c0, 0xc4201452d0, 0xc4205daa77, 0xc420b3c5fa)
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/Users/renier/Projects/go/src/github.com/softlayer/terraform-provider-softlayer/softlayer/resource_softlayer_virtual_guest.go:543 +0x4a4
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: github.com/softlayer/terraform-provider-softlayer/softlayer.resourceSoftLayerVirtualGuestCreate(0xc4207bff20, 0x7113c0, 0xc4201452d0, 0x739a40, 0xcaf1)
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/Users/renier/Projects/go/src/github.com/softlayer/terraform-provider-softlayer/softlayer/resource_softlayer_virtual_guest.go:506 +0x6c3
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420833e60, 0xc420015720, 0xc42083eb40, 0x7113c0, 0xc4201452d0, 0x1, 0xc4205c6450, 0x0)
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/Users/renier/Projects/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:162 +0x30e
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420840390, 0xc4200156d0, 0xc420015720, 0xc42083eb40, 0x0, 0x18, 0x18)
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/Users/renier/Projects/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:178 +0x9b
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4205a6140, 0xc42083e5c0, 0xc42054fd70, 0x0, 0x0)
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/Users/renier/Projects/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:460 +0x57
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: reflect.Value.call(0xc42001a960, 0xc42002c088, 0x13, 0x82b8b1, 0x4, 0xc4205dbec0, 0x3, 0x3, 0x0, 0x0, ...)
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/usr/local/go/src/reflect/value.go:434 +0x5c8
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: reflect.Value.Call(0xc42001a960, 0xc42002c088, 0x13, 0xc4205dbec0, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: net/rpc.(*service).call(0xc42066a0c0, 0xc42066a080, 0xc42000d940, 0xc42057a400, 0xc4205a6ea0, 0x699240, 0xc42083e5c0, 0x16, 0x699280, 0xc42054fd70, ...)
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/usr/local/go/src/net/rpc/server.go:383 +0x148
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: created by net/rpc.(*Server).ServeCodec
2016/11/16 15:34:44 [DEBUG] plugin: terraform-provider-softlayer: 	/usr/local/go/src/net/rpc/server.go:477 +0x421
2016/11/16 15:34:44 [DEBUG] root.esg-mq: eval: *terraform.EvalWriteState
2016/11/16 15:34:44 [DEBUG] root.esg-mq: eval: *terraform.EvalApplyProvisioners
2016/11/16 15:34:44 [DEBUG] root.esg-mq: eval: *terraform.EvalIf
2016/11/16 15:34:44 [DEBUG] root.esg-mq: eval: *terraform.EvalWriteState
2016/11/16 15:34:44 [DEBUG] root.esg-mq: eval: *terraform.EvalWriteDiff
2016/11/16 15:34:44 [DEBUG] root.esg-mq: eval: *terraform.EvalApplyPost
2016/11/16 15:34:44 [ERROR] root.esg-mq: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* softlayer_virtual_guest.vsi: unexpected EOF
```

**Comment by renier** [comment]
@igoraj which version or commit are you at?

**Comment by igoraj** [comment]
@renier i'm on 1.2.0

**Comment by renier** [comment]
@igoraj Thanks for reporting. This should be fixed on master. Please try it out and let me know.

**Comment by igoraj** [comment]
@renier thanks, will play with it tomorrow and let you know.

**Comment by igoraj** [comment]
@renier sorry to report but it happened again and pretty much looks the same:

```
panic: runtime error: invalid memory address or nil pointer dereference
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc000c]
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: goroutine 270 [running]:
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: panic(0x73fd80, 0xc42000c0b0)
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /usr/local/go/src/runtime/panic.go:500 +0x1a1
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: github.com/softlayer/terraform-provider-softlayer/softlayer.resourceSoftLayerVirtualGuestRead(0xc420406e40, 0x726d20, 0xc420650620, 0xc420918a77, 0xc4206e96ea)
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /Users/renier/Projects/go/src/github.com/softlayer/terraform-provider-softlayer/softlayer/resource_softlayer_virtual_guest.go:556 +0x6ac
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: github.com/softlayer/terraform-provider-softlayer/softlayer.resourceSoftLayerVirtualGuestCreate(0xc420406e40, 0x726d20, 0xc420650620, 0x0, 0xcaf1)
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /Users/renier/Projects/go/src/github.com/softlayer/terraform-provider-softlayer/softlayer/resource_softlayer_virtual_guest.go:507 +0x6c3
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4207ff080, 0xc420120370, 0xc4208a78e0, 0x726d20, 0xc420650620, 0x1, 0xc42064a510, 0x18)
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /Users/renier/Projects/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:162 +0x30e
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420805500, 0xc4201202d0, 0xc420120370, 0xc4208a78e0, 0x0, 0x0, 0x0)
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /Users/renier/Projects/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:178 +0x9b
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4207f2900, 0xc4208a73a0, 0xc4208e2b50, 0x0, 0x0)
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /Users/renier/Projects/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:460 +0x57
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: reflect.Value.call(0xc42001ab40, 0xc4206cdee0, 0x13, 0x84292b, 0x4, 0xc420919ec0, 0x3, 0x3, 0x0, 0x0, ...)
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /usr/local/go/src/reflect/value.go:434 +0x5c8
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: reflect.Value.Call(0xc42001ab40, 0xc4206cdee0, 0x13, 0xc420919ec0, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /usr/local/go/src/reflect/value.go:302 +0xa4
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: net/rpc.(*service).call(0xc4207eea00, 0xc4207ee9c0, 0xc4207f0b60, 0xc420699080, 0xc4207f2f40, 0x6ae140, 0xc4208a73a0, 0x16, 0x6ae180, 0xc4208e2b50, ...)
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /usr/local/go/src/net/rpc/server.go:383 +0x148
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer: created by net/rpc.(*Server).ServeCodec
2016/11/18 10:27:45 [DEBUG] plugin: terraform-provider-softlayer:   /usr/local/go/src/net/rpc/server.go:477 +0x421
2016/11/18 10:27:45 [DEBUG] root.esp-as: eval: *terraform.EvalWriteState
2016/11/18 10:27:45 [DEBUG] root.esp-as: eval: *terraform.EvalApplyProvisioners
2016/11/18 10:27:45 [DEBUG] root.esp-as: eval: *terraform.EvalIf
2016/11/18 10:27:45 [DEBUG] root.esp-as: eval: *terraform.EvalWriteState
2016/11/18 10:27:45 [DEBUG] root.esp-as: eval: *terraform.EvalWriteDiff
2016/11/18 10:27:45 [DEBUG] root.esp-as: eval: *terraform.EvalApplyPost
2016/11/18 10:27:45 [ERROR] root.esp-as: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* softlayer_virtual_guest.vsi: unexpected EOF
2016/11/18 10:27:45 [TRACE] [walkApply] Exiting eval tree: softlayer_virtual_guest.vsi
2016/11/18 10:27:45 [DEBUG] plugin: /Users/igor/go/bin/terraform-provider-softlayer: plugin process exited
```

terraform version: v0.7.10
softlayer plugin version: 1.3.0

**Comment by renier** [comment]
@igoraj That's a different line that it is panicking on. It means that when we read the VM from SLAPI, it is not getting back the private IP address, which should never happen.

Can you share your .tf configuration?

**Comment by igoraj** [comment]
@renier sure, it's quite simple as we have just started to play with terraform

```
provider "softlayer" {}

resource "softlayer_virtual_guest" "vsi" {
  count           = "${var.num}"
  cores           = "${var.cpu}"
  memory          = "${var.ram}"
  private_vlan_id = "${var.private_vlan_id}"

  #    disks = "${var.disks}"   # disabled due to issue with softlayer when using custom images
  hostname = "${var.name}${count.index}"
  domain   = "${var.domain}"
  image_id = <custom_image_id>
  ssh_key_ids = ["<ssh_key_id>"]

  datacenter     = "${lookup(var.datacenters, var.datacenter)}"
  local_disk     = false
  hourly_billing = true

  tags = "${var.tags}"

  private_network_only    = true
  post_install_script_uri = "https://api.service.softlayer.com/rest/v3/SoftLayer_Resource_Metadata/UserMetadata.txt"
  user_metadata           = "${data.template_file.bootstrap_phase0.rendered}"
}

data "template_file" "bootstrap_phase0" {
  template = "${file("bootstrap_phase0.sh")}"

  vars {
    "ENVIRONMENT" = "${var.environment}"
  }
}
```

**Comment by renier** [comment]
@igoraj Can you try testing by building a new binary from master? e451d46

**Comment by igoraj** [comment]
@renier sure, but it does not happen every time, so it may take a day or too again before you hear from me again :) many thanks for prompt fix 👍

**Comment by igoraj** [comment]
@renier so far so good, haven't seen any more crashes.
